wandb_version: 1

config:
  desc: null
  value: config/general_config.yaml
wandb_project_name:
  desc: null
  value: NonconvexSampling
tags:
  desc: null
  value: experiments
mode:
  desc: null
  value: sample
score_method:
  desc: null
  value: p0t
p0t_method:
  desc: null
  value: rejection
dimension:
  desc: null
  value: 5
reuse_samples:
  desc: null
  value: 'no'
max_iters_optimization:
  desc: null
  value: 50
num_sampler_iterations:
  desc: null
  value: 100
ula_step_size:
  desc: null
  value: 0.001
num_estimator_batches:
  desc: null
  value: 1
num_estimator_samples:
  desc: null
  value: 10000
eps_stable:
  desc: null
  value: 1.0e-09
num_recursive_steps:
  desc: null
  value: 2
rdmc_initial_condition:
  desc: null
  value: normal
sde_type:
  desc: null
  value: vp
multiplier:
  desc: null
  value: 0.0
bias:
  desc: null
  value: 2.0
sampling_method:
  desc: null
  value: ei
num_batches:
  desc: null
  value: 1
sampling_batch_size:
  desc: null
  value: 1000
T:
  desc: null
  value: 5.0
sampling_eps:
  desc: null
  value: 0.005
disc_steps:
  desc: null
  value: 25
ula_steps:
  desc: null
  value: 0
density:
  desc: null
  value: block_independent
density_parameters_path:
  desc: null
  value: null
discontinuity:
  desc: null
  value: false
f:
  desc: null
  value: ''
_wandb:
  desc: null
  value:
    python_version: 3.11.14
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1764408375.408723
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.11.14
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
